"use strict";
const zh={"t0":"跳转至正文","t1":"产品","t2":"采购流程","t3":"公司","t4":"联系我们","t5":"中国汽车配件<br>采购与供应。","t6":"按您的清单选品，确认订单，协调中国发货。","t7":"沟通采购需求","t8":"公司宣传册 PDF ↗","t9":"按零件号 · 按样品 · 按包装需求","t10":"滤清器 · 产品样品","t11":"主要产品类别","t12":"下单前确认适配信息、数量及包装要求。","t13":"滤清器","t14":"机油、空气及空调滤清器","t15":"制动系统","t16":"刹车片与制动盘","t17":"传动皮带","t18":"按标识与尺寸匹配","t19":"车身配件","t20":"按车型与照片匹配","t21":"轮毂","t22":"按需求确认尺寸及适配","t23":"没有找到所需配件？","t24":"发送零件号清单与数量，我们将核实采购可行性。","t25":"沟通采购清单 →","t26":"图片展示品类与样品，供货情况、配置和交期以具体报价确认为准。","t27":"采购如何推进","t28":"每个环节都有明确的确认内容。","t29":"提交需求","t30":"提供零件号、数量、照片与收货城市。","t31":"确认方案","t32":"核对规格、价格、包装与预计交期。","t33":"备货核对","t34":"约定检验范围，协调发货前照片确认。","t35":"协调发运","t36":"确认运输路线、单据与货物交接条件。","t37":"其他配套","t38":"订单集货 · 品牌包装 · 发货协调","t39":"禾溯 · 义乌","t40":"我们在中国开展汽车配件采购业务，直接沟通客户需求，协调订单备货与发运。","t41":"所在地","t42":"中国 · 浙江 · 义乌","t43":"联系电话","t44":"公司办公室 · 禾溯实拍","t45":"公司门牌","t46":"货物发运 · 公司提供照片","t47":"询价需要哪些信息","t48":"需求信息越准确，越便于确认所需配件。","t49":"零件号或 OEM 号；如有，请提供标识照片。","t50":"车型、生产年份及所需参数。","t51":"数量、包装要求及收货城市。","t52":"从您的配件清单开始。","t53":"请准备零件号、数量与收货城市，我们将根据具体需求沟通供货条件。","t54":"中国 · 浙江 · 义乌","t55":"采购需求","t56":"零件号 / 产品描述","t57":"数量","t58":"收货城市","t59":"生成询价文本","t60":"此表单生成可复制的询价文本，不会自动发送。","t61":"询价文本","t62":"复制文本","t63":"下载文本","t64":"公司宣传册 PDF ↗"};
const elements=[...document.querySelectorAll('[data-i18n]')];
const ru=Object.fromEntries(elements.map(el=>[el.dataset.i18n,el.innerHTML]));
let language='ru';
function switchLanguage(next){language=next;document.documentElement.lang=language==='zh'?'zh-CN':'ru';elements.forEach(el=>el.innerHTML=(language==='zh'?zh:ru)[el.dataset.i18n]);document.getElementById('language').textContent=language==='zh'?'Русский':'中文';document.getElementById('status').textContent='';document.title=language==='zh'?'禾溯 TRACEROOT — 汽车配件采购与供应':'TRACEROOT — Автозапчасти из Китая';try{localStorage.setItem('traceroot-language',language);}catch{}}
document.getElementById('language').addEventListener('click',()=>switchLanguage(language==='ru'?'zh':'ru'));
try{if(localStorage.getItem('traceroot-language')==='zh')switchLanguage('zh');}catch{}
document.getElementById('inquiry-form').addEventListener('submit',e=>{e.preventDefault();const fields=['parts','quantity','destination'].map(id=>document.getElementById(id));for(const field of fields){if(!field.value.trim()){field.setCustomValidity(language==='zh'?'请填写此项。':'Заполните поле.');field.reportValidity();field.addEventListener('input',()=>field.setCustomValidity(''),{once:true});return;}}const labels=language==='zh'?['产品 / 零件号','数量','收货城市']:['Детали / артикулы','Количество','Город доставки'];document.getElementById('message').value='TRACEROOT — '+(language==='zh'?'采购询价':'Запрос предложения')+'\n\n'+fields.map((f,i)=>labels[i]+': '+f.value.trim()).join('\n');document.getElementById('result').hidden=false;document.getElementById('status').textContent='';});
document.getElementById('copy').addEventListener('click',async()=>{const field=document.getElementById('message');try{await navigator.clipboard.writeText(field.value);document.getElementById('status').textContent=language==='zh'?'已复制，请通过您常用的联系方式发送。':'Скопировано. Отправьте текст привычным способом связи.';}catch{field.focus();field.select();document.getElementById('status').textContent=language==='zh'?'请手动复制选中的文本。':'Скопируйте выделенный текст вручную.';}});
document.getElementById('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+document.getElementById('message').value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TRACEROOT-request.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
