'use strict';
const zh={phoneLabel:'联系电话',skip:'跳到主要内容',navProducts:'产品类别',navServices:'服务流程',navCompany:'关于禾溯',navInquiry:'洽谈采购',heroEyebrow:'中国 · 义乌 / 汽车配件采购',heroTitle1:'中国汽配，',heroTitle2:'连接你的生意。',heroDescription:'从一份配件清单，到备妥待发的货物。禾溯为你协调选品、采购与集货，让每笔订单有据可循。',heroPhoto:'产品实拍',explore:'了解产品类别',brochure:'公司宣传册 <span>PDF</span>',heroBottom:'立足中国。与你保持联系。',scroll:'向下探索',principle1:'按需求匹配产品',principle2:'发运前核对检查',principle3:'多供应商订单集货',productsEyebrow:'01 / 产品类别',productsTitle:'每一次采购，<br>从合适的配件开始。',productsIntro:'按零件号、车型或样品寻找产品。适配信息与供货情况，在下单前逐一确认。',catFilters:'滤清器',catBrakes:'制动系统',catBelts:'传动皮带',catBody:'车身配件',catWheels:'轮毂',moreProducts:'其他可询产品：悬挂、发动机配件、电气系统、传动系统与冷却系统。',productImageLabel:'产品样品实拍',productInquiry:'加入询价 <span>+</span>',servicesEyebrow:'02 / 服务流程',servicesTitle:'从需求确认，<br>到备货发运。',servicesIntro:'先把产品和条件说清楚，再安排采购与出运。每个环节，都围绕你的实际订单展开。',step1Title:'选品与报价',step1Text:'确认零件号、数量及要求，核对价格、起订量和备货时间。',step2Title:'采购与检查',step2Text:'协调下单，按约定内容核对标识、数量及货物外观。',step3Title:'集货与包装',step3Text:'汇总不同供应商的货物，确认包装、重量、体积与唛头。',step4Title:'安排运输',step4Text:'根据目的地和货物情况确认路线、运输费用与单证要求。',logisticsEyebrow:'集货与发运',logisticsTitle:'不同的供应商，<br>一起发出的货。',logisticsText:'将不同采购订单集中整理后安排发运，结合货物特点与目的城市选择运输方式。',rail:'铁路',road:'公路',sea:'海运',companyEyebrow:'03 / 关于禾溯',companyTitle:'在中国，<br><em>与你并肩。</em>',companyText:'禾溯是一家位于浙江义乌的贸易公司，为客户协调中国汽配采购，以及订单汇总和发运准备。',companyText2:'支持俄语沟通。从具体产品、采购要求到交付条件，让双方始终围绕同一份订单沟通。',officeCaption:'我们的办公空间',signCaption:'TRACEROOT · 义乌禾溯',detailCaption:'日常工作场景',brandEyebrow:'04 / 品牌定制',brandTitle:'让你的品牌，<br>出现在产品上。',brandText:'协调包装设计、文字语言、产品标识与样品确认。标志印制方式和起订量，依据具体产品确定。',brandTag1:'设计稿',brandTag2:'样品',brandTag3:'标识',brandTag4:'批量包装',brandAction:'洽谈包装需求 <span>+</span>',inquiryEyebrow:'05 / 从你的采购清单开始',inquiryTitle:'你在寻找<br><em>什么？</em>',inquiryText:'填写零件号、数量和收货城市，整理成一份清晰的询价需求，发送给与你对接的禾溯经理。',downloadBrochure:'下载公司宣传册 <span>PDF · 9页</span>',nameLabel:'称呼 / 公司',cityLabel:'收货城市',namePlaceholder:'你的公司名称',cityPlaceholder:'城市、国家',categoryLabel:'产品类别',catGeneral:'多个类别 / 其他产品',catBrand:'自有品牌包装',detailsLabel:'零件号、数量与其他要求',detailsPlaceholder:'配件清单、车型 / VIN、数量、包装要求等…',localNote:'信息只在当前浏览器中处理。此步骤生成询价文本，不会自动发送。',prepare:'生成询价文本',resultTitle:'询价文本已整理',edit:'修改',resultText:'复制后发送给与你对接的经理，也可以保存为文本文件。',copy:'复制文本',save:'保存 .txt',footerBrand:'义乌禾溯 · 贸易服务',footerLocation:'中国 · 浙江 · 义乌<br>支持俄语沟通',toTop:'回到顶部',footerNote:'具体产品及供货条件，以双方确认结果为准。'};
const ru={};
document.querySelectorAll('[data-i18n]').forEach(el=>{ru[el.dataset.i18n]=el.innerHTML;});
document.querySelectorAll('[data-placeholder]').forEach(el=>{ru[el.dataset.placeholder]=el.placeholder;});
const products={filters:{key:'catFilters',description:{ru:'Масляные, воздушные и салонные фильтры. Подбор под модель и артикул.',zh:'机油、空气及空调滤清器。依据车型和零件号匹配。'}},brakes:{key:'catBrakes',description:{ru:'Тормозные колодки и накладки. Уточняем применимость и требования к материалу.',zh:'刹车片与制动衬片。确认适配车型及材料要求。'}},belts:{key:'catBelts',description:{ru:'Приводные ремни. Согласуем профиль, длину и совместимость с вашим узлом.',zh:'传动皮带。核对截面、长度和适配部件。'}},body:{key:'catBody',description:{ru:'Бамперы, решётки и другие кузовные детали. Проверяем модель и год выпуска.',zh:'保险杠、格栅及其他车身配件。核对车型和年份。'}},wheels:{key:'catWheels',description:{ru:'Колёсные диски. Размеры и параметры крепления согласуем до заказа.',zh:'汽车轮毂。下单前确认尺寸与安装参数。'}}};
let currentLanguage='ru';let currentProduct='filters';let resultReady=false;
const $=id=>document.getElementById(id);
function dictionary(){return currentLanguage==='zh'?zh:ru;}
function plain(key){return (dictionary()[key]||'').replace(/<[^>]*>/g,'');}
function selectProduct(key,focus=false){if(!Object.hasOwn(products,key))throw new Error('Unknown product category');currentProduct=key;document.querySelectorAll('[data-product]').forEach(button=>{const selected=button.dataset.product===key;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;if(selected&&focus)button.focus();});$('product-panel').setAttribute('aria-labelledby','tab-'+key);$('product-image').src='assets/'+key+'.webp';$('product-image').alt=plain(products[key].key);$('product-image').style.objectFit=(key==='wheels'||key==='body')?'contain':'cover';$('product-title').textContent=plain(products[key].key);$('product-description').textContent=products[key].description[currentLanguage];}
function setLanguage(language){if(!['ru','zh'].includes(language))return;currentLanguage=language;const map=dictionary();document.documentElement.lang=language==='zh'?'zh-CN':'ru';document.querySelectorAll('[data-i18n]').forEach(el=>{const v=map[el.dataset.i18n];if(v!==undefined)el.innerHTML=v;});document.querySelectorAll('[data-placeholder]').forEach(el=>{el.placeholder=map[el.dataset.placeholder]||'';});$('language').innerHTML=language==='ru'?'RU <span>/ 中文</span>':'中文 <span>/ RU</span>';$('language').setAttribute('aria-label',language==='ru'?'切换到中文':'Переключить на русский');document.title=language==='ru'?'TRACEROOT — Автозапчасти из Китая':'TRACEROOT 禾溯 — 中国汽配采购与供应服务';document.querySelector('meta[name="description"]').content=language==='ru'?'TRACEROOT. Подбор и закупка автозапчастей в Китае, проверка, консолидация и организация доставки. Иу, Чжэцзян.':'禾溯 TRACEROOT，位于中国义乌。提供汽车配件选品、采购协调、订单集货与发运安排。';const labels=language==='zh'?['滤清器与汽车配件样品','已装载待发运的运输车辆','禾溯办公空间','义乌禾溯 TRACEROOT 公司铭牌','办公室日常场景','自有品牌汽配包装样品']:['Фильтры и образцы автозапчастей','Подготовленный к перевозке груз на автомобиле','Офис TRACEROOT','Фирменная табличка TRACEROOT','Рабочая обстановка в офисе','Образец фирменной упаковки автозапчастей'];['.hero-photo img','.logistics-image img','.office-photo img','.sign-photo img','.detail-photo img','.private-image img'].forEach((sel,i)=>document.querySelector(sel).alt=labels[i]);document.querySelector('.product-list').setAttribute('aria-label',language==='zh'?'汽车配件类别':'Категории автозапчастей');selectProduct(currentProduct);updateMenuLabel();if(resultReady)$('request-output').value=buildRequest(readForm());$('copy-status').textContent='';try{localStorage.setItem('traceroot-language',language);}catch{}}
$('language').addEventListener('click',()=>setLanguage(currentLanguage==='ru'?'zh':'ru'));
function updateMenuLabel(){const open=$('menu-button').getAttribute('aria-expanded')==='true';$('menu-button').setAttribute('aria-label',currentLanguage==='zh'?(open?'关闭菜单':'打开菜单'):(open?'Закрыть меню':'Открыть меню'));}
function closeMenu(){$('mobile-nav').hidden=true;$('menu-button').setAttribute('aria-expanded','false');updateMenuLabel();}
$('menu-button').addEventListener('click',()=>{const open=$('menu-button').getAttribute('aria-expanded')==='true';$('mobile-nav').hidden=open;$('menu-button').setAttribute('aria-expanded',String(!open));updateMenuLabel();});
$('mobile-nav').querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('mobile-nav').hidden){closeMenu();$('menu-button').focus();}});document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});
document.querySelectorAll('[data-product]').forEach((button,index)=>{button.addEventListener('click',()=>selectProduct(button.dataset.product));button.addEventListener('keydown',event=>{const keys=['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();const list=Object.keys(products);let target=index;if(['ArrowDown','ArrowRight'].includes(event.key))target=(index+1)%list.length;if(['ArrowUp','ArrowLeft'].includes(event.key))target=(index-1+list.length)%list.length;if(event.key==='Home')target=0;if(event.key==='End')target=list.length-1;selectProduct(list[target],true);});});
function showForm(){$('inquiry-form').hidden=false;$('request-result').hidden=true;resultReady=false;}
$('product-inquiry').addEventListener('click',()=>{showForm();$('inquiry-category').value=currentProduct;$('inquiry').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('customer-name').focus({preventScroll:true});});
document.querySelector('.private-copy>a').addEventListener('click',()=>{showForm();$('inquiry-category').value='brand';});
function readForm(){return {name:$('customer-name').value.trim(),city:$('delivery-city').value.trim(),category:$('inquiry-category').value,details:$('inquiry-details').value.trim()};}
function validateRequest(input){if(!input||typeof input!=='object')throw new Error('Request must be an object');const fields={name:120,city:120,details:5000};const result={};for(const [key,max]of Object.entries(fields)){if(typeof input[key]!=='string'||!input[key].trim()||input[key].length>max)throw new Error('Invalid '+key);result[key]=input[key].trim();}if(!['general',...Object.keys(products),'brand'].includes(input.category))throw new Error('Invalid category');result.category=input.category;return result;}
function categoryLabel(key){return key==='general'?plain('catGeneral'):key==='brand'?plain('catBrand'):plain(products[key].key);}
function buildRequest(data){const zhMode=currentLanguage==='zh';return (zhMode?'禾溯 TRACEROOT｜采购询价':'TRACEROOT | Запрос на поставку')+'\n\n'+(zhMode?'公司 / 称呼：':'Имя / компания: ')+data.name+'\n'+(zhMode?'收货城市：':'Город доставки: ')+data.city+'\n'+(zhMode?'产品类别：':'Категория: ')+categoryLabel(data.category)+'\n\n'+(zhMode?'采购需求：':'Детали запроса:')+'\n'+data.details+'\n\n'+(zhMode?'请确认供货情况、价格、起订量及备货时间。':'Просим уточнить доступность, цену, минимальную партию и срок готовности.');}
function prepareRequest(input){const data=validateRequest(input);$('customer-name').value=data.name;$('delivery-city').value=data.city;$('inquiry-category').value=data.category;$('inquiry-details').value=data.details;$('request-output').value=buildRequest(data);$('inquiry-form').hidden=true;$('request-result').hidden=false;$('copy-status').textContent='';resultReady=true;return {status:'prepared_not_sent',text:$('request-output').value};}
$('inquiry-form').addEventListener('submit',event=>{event.preventDefault();const data=readForm();if(!data.name||!data.city||!data.details){const field=!data.name?$('customer-name'):!data.city?$('delivery-city'):$('inquiry-details');field.setCustomValidity(currentLanguage==='zh'?'请填写此项，不能只有空格。':'Заполните поле: пробелы не считаются значением.');field.reportValidity();field.addEventListener('input',()=>field.setCustomValidity(''),{once:true});return;}prepareRequest(data);$('request-output').focus({preventScroll:true});});
$('edit-request').addEventListener('click',()=>{showForm();$('customer-name').focus({preventScroll:true});});
$('copy-request').addEventListener('click',async()=>{const output=$('request-output');try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(output.value);$('copy-status').textContent=currentLanguage==='zh'?'已复制，请粘贴给与你对接的经理。':'Скопировано. Отправьте текст вашему менеджеру.';}catch{output.focus();output.select();$('copy-status').textContent=currentLanguage==='zh'?'文本已选中，请使用系统“复制”功能。':'Текст выделен. Используйте команду «Копировать» на устройстве.';}});
$('download-request').addEventListener('click',()=>{const blob=new Blob(['\uFEFF'+$('request-output').value],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='TRACEROOT-request.txt';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}});},{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.documentElement.classList.add('js-motion');}
window.addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>20),{passive:true});
try{if(localStorage.getItem('traceroot-language')==='zh')setLanguage('zh');}catch{}
// Optional page-scoped agent interface; mirrors the local request preparation form.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'prepare_traceroot_request',title:'Prepare a TRACEROOT sourcing request',description:'Fill the visible form and prepare a local inquiry text. Does not send or submit the request to the company.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:120},city:{type:'string',minLength:1,maxLength:120},category:{type:'string',enum:['general','filters','brakes','belts','body','wheels','brand']},details:{type:'string',minLength:1,maxLength:5000}},required:['name','city','category','details'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{const result=prepareRequest(input);$('inquiry').scrollIntoView({behavior:'instant'});return result;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
